import { createTsupConfig } from "@sometic/build-config";

export default createTsupConfig({
    entry: {
        index: "src/index.ts",
        "button/index": "src/button/index.ts",
        "input/index": "src/input/index.ts",
        "form/index": "src/form/index.ts",
        "auth/index": "src/auth/index.ts",
        "selection/index": "src/selection/index.ts",
        "overlay/index": "src/overlay/index.ts",
        "structure/index": "src/structure/index.ts",
        "shared/events": "src/shared/events.ts",
    },
    external: [
        "@sometic/auth",
        "@sometic/date-core",
        "@sometic/date-native",
        "@sometic/dom",
        "@sometic/dom/button",
        "@sometic/dom/icon-button",
        "@sometic/dom/toggle-button",
        "@sometic/dom/button-group",
        "@sometic/dom/async-button",
        "@sometic/dom/field",
        "@sometic/dom/input",
        "@sometic/dom/input-password",
        "@sometic/dom/input-otp",
        "@sometic/dom/input-number",
        "@sometic/dom/input-file",
        "@sometic/dom/input-masked",
        "@sometic/dom/input-currency",
        "@sometic/dom/input-date",
        "@sometic/dom/checkbox",
        "@sometic/dom/radio",
        "@sometic/dom/switch",
        "@sometic/dom/select",
        "@sometic/dom/overlay",
        "@sometic/dom/dialog",
        "@sometic/dom/popover",
        "@sometic/dom/tooltip",
        "@sometic/dom/toast",
        "@sometic/dom/alert",
        "@sometic/dom/badge",
        "@sometic/dom/progress",
        "@sometic/dom/spinner",
        "@sometic/dom/skeleton",
        "@sometic/positioning",
        "@sometic/forms",
        "@sometic/forms/a11y",
        "@sometic/validation",
    ],
});
