import { createTsupConfig } from "@sometic/build-config";

export default createTsupConfig({
    entry: {
        index: "src/index.ts",
        "button/index": "src/button/index.ts",
        "field/index": "src/field/index.ts",
        "input/index": "src/input/index.ts",
        "form/index": "src/form/index.ts",
        "auth/index": "src/auth/index.ts",
        "http/index": "src/http/index.ts",
        "head/index": "src/head/index.ts",
        "store/index": "src/store/index.ts",
        "selection/index": "src/selection/index.ts",
        "overlay/index": "src/overlay/index.ts",
        "structure/index": "src/structure/index.ts",
        "query/index": "src/query/index.ts",
        "data/index": "src/data/index.ts",
    },
    external: [
        "vue",
        "@sometic/auth",
        "@sometic/http",
        "@sometic/head",
        "@sometic/query",
        "@sometic/store",
        "@sometic/dom",
        "@sometic/dom/button",
        "@sometic/dom/icon-button",
        "@sometic/dom/toggle-button",
        "@sometic/dom/async-button",
        "@sometic/dom/button-group",
        "@sometic/dom/field",
        "@sometic/dom/input",
        "@sometic/dom/input-password",
        "@sometic/dom/input-otp",
        "@sometic/dom/input-number",
        "@sometic/dom/input-file",
        "@sometic/dom/input-masked",
        "@sometic/dom/input-currency",
        "@sometic/dom/input-date",
        "@sometic/dom/checkbox",
        "@sometic/dom/radio",
        "@sometic/dom/switch",
        "@sometic/dom/select",
        "@sometic/dom/dialog",
        "@sometic/dom/popover",
        "@sometic/dom/tooltip",
        "@sometic/dom/toast",
        "@sometic/dom/alert",
        "@sometic/dom/data-table",
        "@sometic/dom/upload",
        "@sometic/dom/permission-matrix",
        "@sometic/dom/notification-center",
        "@sometic/dom/status",
        "@sometic/date-core",
        "@sometic/forms",
        "@sometic/forms/schema-form",
    ],
});
