import { createTsupConfig } from "@sometic/build-config";

export default createTsupConfig({
    entry: {
        index: "src/index.ts",
        "button/index": "src/button/index.ts",
        "icon-button/index": "src/icon-button/index.ts",
        "toggle-button/index": "src/toggle-button/index.ts",
        "async-button/index": "src/async-button/index.ts",
        "button-group/index": "src/button-group/index.ts",
        "field/index": "src/field/index.ts",
        "input/index": "src/input/index.ts",
        "input-password/index": "src/input-password/index.ts",
        "input-otp/index": "src/input-otp/index.ts",
        "input-number/index": "src/input-number/index.ts",
        "input-file/index": "src/input-file/index.ts",
        "input-masked/index": "src/input-masked/index.ts",
        "input-currency/index": "src/input-currency/index.ts",
        "input-date/index": "src/input-date/index.ts",
        "checkbox/index": "src/checkbox/index.ts",
        "radio/index": "src/radio/index.ts",
        "switch/index": "src/switch/index.ts",
        "select/index": "src/select/index.ts",
        "overlay/index": "src/overlay/index.ts",
        "dialog/index": "src/dialog/index.ts",
        "popover/index": "src/popover/index.ts",
        "tooltip/index": "src/tooltip/index.ts",
        "toast/index": "src/toast/index.ts",
        "alert/index": "src/alert/index.ts",
        "badge/index": "src/badge/index.ts",
        "skeleton/index": "src/skeleton/index.ts",
        "spinner/index": "src/spinner/index.ts",
        "progress/index": "src/progress/index.ts",
        "combobox/index": "src/combobox/index.ts",
        "breadcrumb/index": "src/breadcrumb/index.ts",
        "accordion/index": "src/accordion/index.ts",
        "tabs/index": "src/tabs/index.ts",
        "context-menu/index": "src/context-menu/index.ts",
        "menu/index": "src/menu/index.ts",
        "drawer/index": "src/drawer/index.ts",
    },
    external: [
        "@sometic/core",
        "@sometic/core/async-operation",
        "@sometic/core/controllable-state",
        "@sometic/core/disposable",
        "@sometic/core/id",
        "@sometic/date-core",
        "@sometic/styling",
        "@sometic/styling/slots",
        "@sometic/styling/state",
        "@sometic/styling/styles",
        "@sometic/styling/classes",
        "@sometic/accessibility",
        "@sometic/accessibility/focus",
        "@sometic/accessibility/dismissable",
        "@sometic/accessibility/portal",
        "@sometic/accessibility/scroll-lock",
        "@sometic/accessibility/announcer",
        "@sometic/positioning",
    ],
});
