export {
    createAccordionController,
    resolveAccordion,
    resolveAccordionItem,
    resolveBadge,
    resolveBreadcrumb,
    resolveBreadcrumbItem,
    resolveProgress,
    resolveSkeleton,
    resolveSpinner,
    createTabsController,
    resolveTabPanel,
    resolveTabTrigger,
    resolveTabs,
} from "@sometic/dom";
