import { createTsupConfig } from "@sometic/build-config";

export default createTsupConfig({
    entry: {
        index: "src/index.ts",
        "button/index": "src/button/index.tsx",
        "field/index": "src/field/index.tsx",
        "input/index": "src/input/index.tsx",
        "form/index": "src/form/index.tsx",
        "auth/index": "src/auth/index.tsx",
        "http/index": "src/http/index.tsx",
        "head/index": "src/head/index.tsx",
        "store/index": "src/store/index.ts",
        "selection/index": "src/selection/index.tsx",
        "overlay/index": "src/overlay/index.tsx",
        "structure/index": "src/structure/index.tsx",
        "query/index": "src/query/index.tsx",
        "data/index": "src/data/index.tsx",
    },
    external: [
        "react",
        "react/jsx-runtime",
        "@sometic/auth",
        "@sometic/http",
        "@sometic/head",
        "@sometic/query",
        "@sometic/store",
        "@sometic/dom",
        "@sometic/dom/button",
        "@sometic/dom/icon-button",
        "@sometic/dom/toggle-button",
        "@sometic/dom/async-button",
        "@sometic/dom/button-group",
        "@sometic/dom/field",
        "@sometic/dom/input",
        "@sometic/dom/input-password",
        "@sometic/dom/input-otp",
        "@sometic/dom/input-number",
        "@sometic/dom/input-file",
        "@sometic/dom/input-masked",
        "@sometic/dom/input-currency",
        "@sometic/dom/input-date",
        "@sometic/dom/checkbox",
        "@sometic/dom/radio",
        "@sometic/dom/switch",
        "@sometic/dom/select",
        "@sometic/dom/dialog",
        "@sometic/dom/popover",
        "@sometic/dom/tooltip",
        "@sometic/dom/toast",
        "@sometic/dom/alert",
        "@sometic/dom/badge",
        "@sometic/dom/skeleton",
        "@sometic/dom/spinner",
        "@sometic/dom/progress",
        "@sometic/dom/combobox",
        "@sometic/dom/breadcrumb",
        "@sometic/dom/accordion",
        "@sometic/dom/tabs",
        "@sometic/dom/context-menu",
        "@sometic/dom/menu",
        "@sometic/dom/drawer",
        "@sometic/date-core",
        "@sometic/forms",
        "@sometic/forms/a11y",
        "@sometic/forms/schema-form",
        "@sometic/validation",
        "@sometic/dom/data-table",
        "@sometic/dom/upload",
        "@sometic/dom/permission-matrix",
        "@sometic/dom/notification-center",
        "@sometic/dom/status",
        "@sometic/dom/command-palette",
        "@sometic/dom/tree",
    ],
    esbuildOptions(options) {
        options.jsx = "automatic";
    },
});
