#!/usr/bin/env sh
set -e

files=$(git diff --cached --name-only --diff-filter=ACMR)
if [ -z "$files" ]; then
    exit 0
fi

printf '%s\n' "$files" | tr '\n' '\0' | xargs -0 pnpm exec prettier --write --ignore-unknown
printf '%s\n' "$files" | tr '\n' '\0' | xargs -0 git add --
