name: Docs

on:
    push:
        branches: [main]
    workflow_dispatch:

permissions:
    contents: read

concurrency:
    group: pages
    cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 20
        permissions:
            contents: read
            pages: write
            id-token: write
        steps:
            - name: Checkout
              uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
              with:
                  fetch-depth: 0

            - name: Setup pnpm
              uses: pnpm/action-setup@a15d269cd4658e1107c09f1fabf4cbd7bd1f308a # v4.4.0
              with:
                  version: 10.14.0

            - name: Setup Node.js
              uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
              with:
                  node-version: 22
                  cache: pnpm

            - name: Setup Pages
              uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0

            - name: Install
              run: pnpm install --frozen-lockfile

            - name: Build CDN mirrors for docs
              run: pnpm exec turbo run build --filter=@sometic/http... --filter=@sometic/query... --filter=@sometic/auth... --filter=@sometic/store... --filter=@sometic/theme... --filter=@sometic/head... --filter=@sometic/app-shell... --filter=@sometic/elements... --filter=@sometic/core... --filter=@sometic/events... --filter=@sometic/forms... --filter=@sometic/styling... --filter=@sometic/accessibility... --filter=@sometic/positioning... --filter=@sometic/dom...

            - name: Build docs
              run: pnpm docs:build

            - name: Upload artifact
              uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
              with:
                  path: apps/docs/.vitepress/dist

    deploy:
        needs: build
        runs-on: ubuntu-latest
        name: Deploy
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        permissions:
            pages: write
            id-token: write
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
